#!/usr/bin/env bash
#install Nginx web server

apt-get update
apt-get upgrade
apt-get install nginx
sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html #assign current user to server
sudo chmod -R 755 /var/www
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
