#!/usr/bin/env bash
# /redirect_me redirects to another page
# The redirection must be  "301 moved permanently"

apt -y install nginx
service nginx start
url="location /redirect_me {\n\treturn 301 moved permanently\n}";
sed -i "37i $url" /etc/nginx/sites-available/default
service nginx reload
service nginx restart
