#!/usr/bin/env bash
# Script displays To infinity and beyond indefinitely.
# Script traps a signal

trap 'echo"I am invincible!!!"' SIGTERM
while true;
do
	echo "To infinity and beyond"
	sleep 2
done
