#!/usr/bin/env bash
# Script displays bad luck and good luck for 4th and 8th iteration respectively

x=0
while [ $x -lt 10 ]
do
	if [ $x -eq 3 ]
	then
		echo "bad luck"
	elif [ $x -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( x++ ))
done		
