#!/usr/bin/env bash
# Scripts gives information aout the School file.

file=school
#if school exist

if [[ -s "$file" ]];
then
	echo "school file exists"
	if [[ -s "$file" ]];
	then
		echo "School file is not empty"
	else
		echo "School file is empty"
	fi
	#file is regular file
	if [[ -f "$file" ]];
	then
		echo "School is a regular file"
	fi
else
	echo "School is a regular file"
fi
