#!/usr/bin/env bash
# Bash Script  creates an RSA key pair.
# Private key name is school
# Size in bytes is 4096
# Passphrase is betty

key_name="school"
Key_size=4096
passphrase="betty"

# Initiate the RSA key pair
ssh-keygen -t rsa -b "$key_size" -f "$key_name" -N "$passphrase"
