#!/usr/bin/env bash
# Bash Script  creates an RSA key pair.
# Private key name is school
# Size in bytes is 4096
# Passphrase is betty


# Initiate the RSA key pair
ssh-keygen -t rsa -b 4096 -f school -N betty
